---
- hosts: localhost
  connection: local

  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible-south"
      instance_type: t3.micro
      security_group: default
      region: "ap-south-1"
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network_interfaces:
        - assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        Environment: Testing

    loop:
      - { image: "ami-0f918f7e67a3323f0" , name: "ansible1" }
      - { image: "ami-0f918f7e67a3323f0" , name: "ansible2" }
      